version: '3.4'

services:
  catalogdb:
    image: mongo

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: ApiServices/Catalog/CatalogApi/Dockerfile
volumes:
  mongo_data: